### ISSUE TITLE
Containerized h264 streams

### ISSUE THREAD

**Issue by olealgoritme** [matijagaspar/ws-avc-player#14]
Nice work.
Do you have any plans to implement streaming from containerized h264 streams? E.g mp4, mpeg2-ts etc.

Thank you.

**Comment by matijagaspar** [comment]
Sorry for the very late reply. I haven't worked on this for a while now. 

No I never had the plan to handle containerized streams in a sense that they will be streamed (via the network) and rendered in browsers as such. For that there are better native solutions that work a lot better than what I could achieve with this approach. Also the primary goal of this project was to handle low latency video.

If you just want to playback a existing containerized stream, you could always transcode (it just extracts from container so the operation is fairly cheap) it on the server into a valid format and feed it to the listener on the server.
