### ISSUE TITLE
Question: how to change the canvas size?

### ISSUE THREAD

**Issue by arodrigoca** [matijagaspar/ws-avc-player#5]
Hi, currently I´m using this player for research purposes.

I would like to know how you can change the canvas size, so it's not stretched like the one in the example code. Thank you so much.

**Comment by matijagaspar** [comment]
Yeah I handle the sizing a bit awkwardly in the lib, will fix, you can override it with `!important` on css props

**Comment by matijagaspar** [comment]
Check branch: https://github.com/matijagaspar/ws-avc-player/tree/1.0.0-beta1
