### ISSUE TITLE
not compatible with IE

### ISSUE THREAD

**Issue by waclaw66** [matijagaspar/ws-avc-player#9]
Hello.
Could you please make it compatible with IE? There are used array method expressions, which are not supported by IE.

Thanks.

**Comment by matijagaspar** [comment]
I will look at it after I am done with the audio support which is currently in progress.  I will however need the version of IE you are having problems with.

**Comment by waclaw66** [comment]
Audio sounds great! I would like to have support for IE 11 only, unfortunately still used not negligibly. 

Another thing, I have implemented precise fps rendering based on onPictureDecoded event if you are interested. It would be nice to have this feature within your player.

**Comment by matijagaspar** [comment]
Yeah I also believe is just babel/webpack settings for the polyfills.

What do you mean precise fps rendering, That rendering happens at precise rate or just fps info?

The info would useful in the example for performance debugging I have a little check already that drops frames if client lags behind.

But I am not sure about precise rendering as I am guessing that it requires a bit of buffer and I try to keep delay to a minimum

**Comment by waclaw66** [comment]
Rough example bellow. It works quite fluently. Precise rendering could be optional and fps could be passed as a parameter together with init message payload.

```
var wsavc = new WSAvcPlayer.default({useWorker: false});
document.getElementById('webcam_box').appendChild(wsavc.AvcPlayer.canvas);
wsavc.AvcPlayer.render = false;
var frames = [];
var fps = 20;
var renderStarted = false;
var nexttime = null;

function render(now) {
	if (!nexttime) {
		nexttime = now;
	}
	if (now >= nexttime)
	{
		frame = frames.shift();
		if (frame) {
			wsavc.AvcPlayer.renderFrame(frame);
			nexttime += 1000 / fps;
		}
	}
	if (renderStarted) {
		requestAnimationFrame(render);
	}
}

wsavc.AvcPlayer.onPictureDecoded = function (buffer, width, height, infos) {
	frames.push({
		canvasObj: this.canvasObj,
		data: Uint8Array.from(buffer),
		width: width,
		height: height,
	});
	if (!renderStarted) {
		renderStarted = true;
		nexttime = null;
		requestAnimationFrame(render);
	}
}

wsavc.connect("wss://example.com");
```

**Comment by matijagaspar** [comment]
After a quick check, on caniuse, at this point I will not be able to make the lib support IE 11 due to it's lack of native wasm support (https://caniuse.com/#feat=wasm). This lib relies on a [Browdway.js](https://github.com/mbebenita/Broadway) and it seems it does not support ie 11 (example: http://mbebenita.github.io/Broadway/foxDemo.html).

There would be ways around it, but at best it would result in poor performance. So as some wise man once said: either convice IE to support it, or your users to stop using IE :)

**Comment by waclaw66** [comment]
Didn't realize that there is much bigger problem (wasm) than javascript :) Let's burry IE.
